# Generated by Django 6.0.3 on 2026-04-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlmanaxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bonus', models.CharField(max_length=255)),
                ('resource', models.CharField(max_length=255)),
                ('resource_quantity', models.SmallIntegerField()),
                ('resource_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('reward', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EconomyEntry',
            fields=[
                ('almanaxentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='almanax.almanaxentry')),
                ('job', models.CharField(choices=[('Breeder', 'Breeder'), ('Handyman', 'Handyman'), ('Miner', 'Miner'), ('Farmer', 'Farmer'), ('Lumberjack', 'Lumberjack'), ('Hunter', 'Hunter'), ('Jeweller', 'Jeweller'), ('Fisherman', 'Fisherman'), ('Alchemist', 'Alchemist'), ('Shoemaker', 'Shoemaker'), ('Tailor', 'Tailor'), ('Carver', 'Carver'), ('Artificer', 'Artificer'), ('Smith', 'Smith')], max_length=50)),
            ],
            bases=('almanax.almanaxentry',),
        ),
    ]
