# Generated by Django 6.0.3 on 2026-04-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almanaxentry',
            name='date',
        ),
        migrations.AddField(
            model_name='almanaxentry',
            name='day',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almanaxentry',
            name='month',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almanaxentry',
            name='reward',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
