# Generated by Django 6.0.3 on 2026-04-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanax', '0002_remove_almanaxentry_date_almanaxentry_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almanaxentry',
            name='bonus',
            field=models.CharField(max_length=510),
        ),
    ]
