# Generated by Django 4.2.7 on 2023-11-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
