# Generated by Django 4.2.7 on 2023-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_text', models.CharField(max_length=200)),
            ],
        ),
    ]
