# Generated by Django 4.2.7 on 2023-11-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.level'),
        ),
    ]
