# Generated by Django 5.0.6 on 2024-07-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_answer_emoticon'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='suffle_answers',
            field=models.BooleanField(default=True),
        ),
    ]
