# Generated by Django 5.0.6 on 2024-07-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_question_suffle_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='suffle_answers',
            new_name='shuffle_answers',
        ),
    ]
