# Generated by Django 5.1.10 on 2025-07-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_rename_suffle_answers_question_shuffle_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.PositiveIntegerField(default=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='questions_of_the_day', to='question.question')),
            ],
        ),
    ]
