# Generated by Django 5.1.10 on 2025-10-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_rename_suffle_answers_question_shuffle_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.PositiveIntegerField(default=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsOfTheDayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('questions_of_the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionsoftheday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
