# Generated by Django 5.1.10 on 2025-07-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_questionsoftheday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsoftheday',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
