# Generated by Django 5.1.10 on 2025-10-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_questionsoftheday_questionsofthedayquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsofthedayquestion',
            name='questions_of_the_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.questionsoftheday'),
        ),
    ]
