# Generated by Django 5.1.10 on 2025-10-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_alter_questionsofthedayquestion_questions_of_the_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsoftheday',
            name='time_to_answer_hour',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
