# Generated by Django 5.2.7 on 2025-10-21 11:10

import chaloeil_backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_questionsoftheday_time_to_answer_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=chaloeil_backend.storage_backends.QuestionMediaStorage(), upload_to=chaloeil_backend.storage_backends.rename_file),
        ),
    ]
