# Generated by Django 6.0.4 on 2026-04-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionsoftheday',
            name='number_of_questions',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='questionsoftheday',
            name='time_to_answer_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
