# Generated by Django 6.0.4 on 2026-04-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_question_need_review_question_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOfTheDaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='questionsoftheday',
            name='session',
            field=models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qotd', to='question.questionofthedaysession'),
        ),
    ]
