# Generated by Django 6.0.4 on 2026-04-14 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_questionofthedaysession_questionsoftheday_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionofthedaysession',
            name='number_of_questions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionofthedaysession',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='questionsoftheday',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qotd', to='question.questionofthedaysession'),
        ),
    ]
