# Generated by Django 6.0.4 on 2026-04-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_questionofthedaysession_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsoftheday',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qotd', to='question.questionofthedaysession'),
        ),
    ]
