# Generated by Django 6.0.4 on 2026-04-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_alter_questionsoftheday_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsOfTheDayStandalone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_qotd', to='question.questionofthedaysession')),
            ],
        ),
    ]
