# Generated by Django 6.0.4 on 2026-04-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_questionsofthedaystandalone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_flag_question', 'Can flag question')]},
        ),
    ]
