# fly.toml app configuration file generated for chaloeil-backend on 2023-11-26T06:29:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chaloeil-backend"
primary_region = "ams"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate && python manage.py loaddata level"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"
