# Generated by Django 5.1.10 on 2025-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_qotdstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
