# Generated by Django 5.1.10 on 2025-10-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_questionsoftheday_questionsofthedayquestion'),
        ('stats', '0003_alter_player_discord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerQotd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
                ('question_of_the_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionsoftheday')),
            ],
        ),
    ]
