# Generated by Django 5.1.10 on 2025-10-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_alter_questionsofthedayquestion_questions_of_the_day'),
        ('stats', '0004_playerqotd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerqotd',
            unique_together={('player', 'question_of_the_day')},
        ),
    ]
