# Generated by Django 5.2.7 on 2025-10-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_playerqotd_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='answers',
        ),
    ]
