# Generated by Django 6.0.4 on 2026-04-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_alter_questionsoftheday_session'),
        ('stats', '0007_flagreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questionofthedaysession')),
            ],
        ),
    ]
