# Generated by Django 6.0.4 on 2026-04-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_sessionstatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlagReport',
        ),
    ]
