# Generated by Django 5.0.6 on 2024-11-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(auto_created=True)),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
